version: '2'
services:
  go:
    container_name: minitwit-simulator-api
    image: minitwit-api
    build:
      context: .
    ports:
      - "9000:9000"
    environment:
      - BACKEND=spring
networks:
  default:
    external: true
    name: mini-twit-backend_isolated-network